version: '2.3'

volumes:
  rabbitmq_data:


services:

  rabbitmq-server:
      container_name: rabbitmq-server
      image: rabbitmq:3-management
      ports:
          - 127.0.0.1:5672:5672
          - 45672:15672
      environment:
          - RABBITMQ_DEFAULT_USER=test
          - RABBITMQ_DEFAULT_PASS=test
          - RABBITMQ_DEFAULT_VHOST=events
      volumes:
          - rabbitmq_data:/var/lib/rabbitmq/
      restart: on-failure
      healthcheck:
        test: "exit 0"

